---
output:
  pdf_document: default
  html_document: default
---
```{=latex}
\pagenumbering{roman}
```

```{r include=FALSE}
library(knitr)
```

`r if (knitr:::is_html_output()) '
# Declaration{-}
'`

I, Zeqiang Fang, hereby declare that this dissertation is all my own original work and that all sources have been acknowledged. It is xxx words in length

```{=latex}
% Trigger ToC creation in LaTeX
\setcounter{tocdepth}{3}
\tableofcontents
\listoffigures
\listoftables
```

`r if (knitr:::is_html_output()) '
# Abstract{-}
'`

`r if (knitr:::is_latex_output()) '
# Abstract {.unlisted .unnumbered}
'`

to be done

```{r abstract, echo=FALSE, message=FALSE, warning=FALSE,include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(readxl)
library(fs)
library(here)

# read excel to create a table
read_excel(here("tables", "abbreviations.xlsx"))%>%
  arrange(Term) %>% # i.e. alphabetical order by Term
  knitr::kable(booktabs = TRUE)%>% # booktab = T gives us a pretty APA-ish table
  kable_styling(position = "center")%>%
  row_spec(.,
  row=0,
  bold = TRUE)
```

