# Methodology

## Research Framework

1. Restate my research question
2. Cluster & Multiple Regression
(Figure Flow Chart)

## Data Source and Processing

1. What is my data source from?
1. How I process this data? 
  (Figure Flow Chart)
1. To what extent my processed data represent my research objectives?

### Tech Firms Finding

Max: If you don't plan to measure clusters using data-driven methods like DB-Scan, you will need to justify this decision in the dissertation, especially as some tech clusters are likely to be smaller than TTWAs in practice. You could look at literature on TTWAs to argue that they are a good representation of local economies; you could also argue that limitations in OC address data mean it's sensible to aggregate firms to TTWA level (again, you will need references to back that up).

### Dynamics Measuring Index 

I need to refer to lit review

## Quatitative Analysis and Methods

### Tech Cluster Identifying

sic4 code

tech cluster

### Dynamics Analysis

entry / exit / churn pattern

incorporation / dissolution date

### Location Quotients

## Limitations

## Ethical Statement