--- 
title: CASA0012 Dissertation Book

author: 
- |
    | Zeqiang Fang
    |    
    | CASA0012, MSc Spatial Data Science and Visualisation Dissertation 
    |  
    | Supervisor: Dr Max Nathan
    |
    | Repository: https://fang-zeqiang.github.io/CASA0012-Dissertation/
    |  
    | This dissertation is submitted in part requirement for the 
    | MSc (Or MRes) in the Centre for Advanced Spatial Analysis, 
    | Bartlett Faculty of the Built Environment, UCL
    |
    | Word count:  

date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
    bookdown::gitbook
    bookdown::html_book
documentclass: book
classoption: oneside #openany or #twosides #if two then need to change headers and check margins.
geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
fontsize: 12pt
linestretch: 1.5
bibliography: [book.bib, packages.bib, test.bib]
biblio-style: apa
link-citations: yes
github-repo: fang-zeqiang/CASA0012-Dissertation
description: "This dissertation is submitted in part requirement for the MSc (Or MRes) in the Centre for Advanced Spatial Analysis, Bartlett Faculty of the Built Environment, UCL "
always_allow_html: yes
---
```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{=latex}
\pagenumbering{roman}
```

```{r include=FALSE}
library(knitr)
library(tinytex)
```

`r if (knitr:::is_html_output()) '
# Abstract {-}
'`
`r if (knitr:::is_latex_output()) '
# Abstract {.unlisted .unnumbered}
'`
Some abstract text

