# Introduction{#intro}

```{=latex}
\pagenumbering{arabic} 
```

## Background and Motivation

Silicon Valley and other tech clusters are critical for modern innovation, company competitiveness, and economic performance in this digitalising world(Kerr, 2020). In terms of the development of high-tech industries, UK is becoming increasingly attractive to international investors. And the scale of VC investment in the UK had reached the third level in the world in 2020, even if it is severely affected by the covid-19 epidemic (Tech Nation, 2021). The UK tech startup and scaleup ecosystem are also valued well. Investment and relative infrastructures are friendly for tech companies (ibid).  In fact, high technology companies are often investigated from the dimension of travel to work areas in many fields of research. For example, some reports found that, between 2007 and 2014, the number of creative tech enterprises grew faster than the overall company population in more than nine out of ten of the UK's 228 travel to work area geographies (Mateos-Garcia，2016). 

There are clustering effects existing among the England tech firms. Some research teams such as Baptista (1999) conducted growth model research and dynamic model mining on regional clusters of technology industries and found that the growth rate of the sub-category business of a specific industry in the cluster may be higher than the industry average and a certain agglomeration phenomenon. Some teams also had done research on employment changes in the corresponding technology research and development industry. Also, the employment growth of high-tech small and medium-sized enterprises (SMEs) seems to depend on the initial level of clusters, and the impact of this clustering effect on employment growth varies greatly in geographic scope (Fingleton et al., 2004). Although there are obvious differences in clustering characteristics between the technology industries in the UK and other areas, the cluster effect of the technology industry in the UK did not seem to be weaker than that in the United States (Baptista and Swann, 1999). 

The dynamics characters of clusters can be measured by their entry pattern. Many patterns of industrial dynamics appear to be affected by the process of knowledge creation, gathering, and destruction. This promotes the admission of new businesses, the long-term coexistence of incumbents and newcomers, and their selected or combined withdrawal (Krafft, 2004). In terms of industry clustering pattern and policy formulation, Nathan and Rosso (2015), in response to the development needs of governments for information and communications technology sectors, utilise big data resources to conduct an innovative alternative analysis for all active information and communications technology manufacturers in the UK. This can help researchers to better understand the current condition of the UK's information and communications technology industry. Meanwhile, the approach of spatial autocorrelation analysis is useful for revealing the structure and patterns of economic geographical variables. It can be used to identify not only the country's overall spatial patterns but also specific micro-locations(Stankov and Dragićević, 2015). Our research can employ these methods and background information to explore the technology industry dynamics and obtain sufficient argument evidence.

## Research Question and Objectives

In order to contribute to this field research, the main purpose of this research is to explore the spatial pattern of tech clusters characteristics, introduce quantitative methods to explore the relationship between cluster dynamics, industrial concentration and density. The research will focus on the following main questions:
  
> To what extent will industry mix and firms density affect tech clusters’ dynamics in England area？
  
> How does tech clusters' dynamics spatio-temporal pattern change in England area from 1998 to 2018?
  
The overall experiment will be carried out around the above-mentioned central question. Breaking down the above central issues, the objectives to be achieved at each stage of this research are divided into 5 points as follows

  1. Review the relevant literature on the use of regression models to identify the relationship between company clusters and find the empirical research which employs Moran's index(Moran's I), local indicators of spatial association(LISA) and hot-spot analysis based on the Getis-Ord Gi* method

  2. Processing and filtering data which can represent the dynamics and related characters of each tech cluster area in England from 1998 to 2018

  3. Exploring the relationship between tech cluster dynamics, industry concentration and company density through trend analysis and regression models

  4. Based on the mining and visualisation of related spatial indicators, understand the spatial autocorrelation of relevant indicators and the trend in the temporal dimension among various travel to work areas (TTWAs) within the England area.

  5. Combine with actual policies to provide guidance and recommendations at the company level and the government level based on regression results and spatial model mining results

## Report Structure

This research paper contains 6 chapters. Chapter 2 will first compare and summarise the current research status of tech cluster dynamics in the UK and other parts of the world. In Chapter 3 methodology, the research scale and object will be explained.  Data processing process and index data summarised in different dimensions will be presented. Research design combining multiple quantitative methods will also be included in this chapter. Chapter 4 will analyse the changes in distribution and explore the influence relationship among variables from the overall to the partial. In addition, this chapter will compare the global and local indices for spatio-temporal analysis. Chapter 5 will discuss the experimental results based on the actual relevant policies of the England authority, and give investment suggestions at the government and enterprise levels for the development of the tech industry and discuss the limitations of the research framework. Finally, Chapter 6 will summarise key findings to respond to the research questions and make recommendations for future study and planning strategies.
