# Methodology

## Research Framework

1. Data Clean & Select
1. Identifying Tech Cluster 
1. Measuring the Dynamics & Industry Mix
1. Quantitative Method Research
1. Temporal Qualitative Analysis

In this study, a data set containing all British companies will be cleaned and attribute selected, and technology companies will be identified and screened according to the classification and definition of technology companies on the official website of the British government; before the quantitative study, this study is based on time and The spatial dimension counts the number of technology companies, and calculates the dynamic indicators of enterprise clusters and industrial combination indicators in a specific year and a specific region; then this study conducts multiple regressions, single and double variables Moran index testing to conduct spatial quantitative research, and finally combines Qualitative spatial pattern trend research on the spatial changes of indicators in three different time periods

在本研究中，包含所有英国公司的数据集会被进行数据清洗和属性选择，并且根据英国政府官网对于科技企业的分类定义来进行科技公司的识别与筛选；在定量研究前，本研究基于时间与空间维度对科技公司数量进行统计，并且计算出特定年份特定地区的企业集群动态指标与产业组合指标；紧接着本研究进行多元回归，单双变量的莫兰指数检测来进行空间定量研究，最后结合三个不同时间段的指标空间变化进行定性的空间模式趋势研究

## Data Source and Processing

1. Data Source
1. Data Clean
  1. The large dta file is handled with `read_stata` and `get_chunk` 去进行大数据的分块读取，提高15GB数据的读取速度
  1. 对于`primary_uk_sic_2007`标识字段进行去空，即该列下为空的行都去除，并且把数据类型转成`int32`
  1. 引入2007 sic code表来进行科技产业的判断，参照了ons.gov.uk网站的Science and Technology Classification数据集划分方式，如下表

为了更好识别科学与技术企业对于英国经济的贡献，官方基于2007年英国标准经济活动分类，结合不同数据源头，对科学与技术企业进行分类标签(Office for National Statistics, 2015)

这里参照官方提供的Science and Technology Classification表中Science and Technology indicator来进行所有产业的科技产业定位，得到科技产业的2007 sic code共计168个，约占英国所有产业分类的16%，包括5个产业大类如Digital Technologies, Life Sciences & Healthcare, Publishing & Broadcasting, Other scientific/technological manufacture and Other scientific/technological services，该分类表格详情会附在附件里

`Office for National Statistics, 2015. Identifying Science and Technology Businesses in Official Statistics. [online] London, UK: Office for National Statistics, pp.10-14. Available at: <https://webarchive.nationalarchives.gov.uk/20160105170025/http://www.ons.gov.uk/ons/site-information/using-the-website/rss-news-feeds/index.html> [Accessed 28 July 2021].`



1. Tech Firms Finding —— 5 digital sic7 code & UK
1. 

## Quatitative Analysis and Methods

### Time Range Selection

### Tech Cluster Identifying

Why I choose ttwa

Why ttwa can work as a firms' cluster

### Dynamics Measuring Index

$$ Entry\ Rate_{i,t} = \frac{Incorporating\ Firms_{i,t}}{Total\  Firms_{i}} $$
Where $i$ means location(travel to work area), $t$ means year 

### Dynamics Analysis

### Herfindahl Index

$$ Herfindahl\ Index_{i,t,k} = \frac{Tech\ Firms_{i,t}}{Total\  Firms_{i}} $$
Where `k` represents industry

赫芬达尔—赫希曼指数 [1]  (Herfindahl-Hirschman Index，简称HHI），简称赫芬达尔指数，是一种测量产业集中度的综合指数。它是指一个行业中各市场竞争主体所占行业总收入或总资产百分比的平方和，用来计量市场份额的变化，即市场中厂商规模的离散度。

赫芬达尔一赫希曼指数是计算某一市场上50家最大企业(如果少于50家企业就是所有企业)每家企业市场占有份额(取百分之的分子)的平方之和。显然， HHI越大，表示市场集中程度越高，垄断程度越高。该指数不仅能反映市场内大企业的市场份额，而且能反映大企业之外的市场结构，因此，能更准确地反映大企业对市场的影响程度。

## Limitations

1. missing data
`diss_year` have 99% missing value

1. ttwa
- ttwa might not be a data-driven method
- ttwa的时间局限性，因为是2015年统计的
- ttwa的变化(Ozkul,2014)

Ozkul, B., 2014. Changing home-to-work travel in England and Wales. Regional Studies, Regional Science, 1(1), pp.32-39.

1. Herfindahl-Hirschman Index
- 

## Ethical Statement

The data for this project comes from OpenCorporates, a firm which aggregates company-level data from around the world [link to their website]. In this case, OpenCorporates have taken data from the UK Companies House register [link to Companies House]. As detailed by Nathan and Rosso (2015), all limited companies in the UK need to registers with Companies House when they are set up, and provide annual returns and financial statements. These include details of directors and company secretary, registered office address, shares and shareholders, as well as company type and principal business activity. Thus, all the data used here is already in the public domain.

The research objectives are tech firms in the UK for this project and the individual data will not be collected and measured in this project. For issues of deanonymisation or privacy, traceable information such as the real companies name and ID will not be utilised in the research. The raw data will be cleaned and filtered by several key variables include industries instead of the company’s name or other sensitive information before doing the research. Through data cleaning, pre-processing, desensitisation or other processing methods, the risks of damage to company interests (such as social reputation, economic benefits and etc.) will be mitigated to an as low as possible level in the research process.

Besides, this project will not cause discrimination of industries or job categories. The final analysis results, such as the different industry concentration in each region, will not deepen some people's stereotypes and prejudices about the region (This content will be fully discussed in the project discussion section). It is necessary to point out and declare the objectivity of the analysis and the non-absoluteness of the results in the disclaimer. Consider the feelings of people and governments in different parts of the UK, this research will prevent the influence of personal preferences and subjective emotions.

The leakage of companies' name and information will be protected. For example, in the reflection of the results section of academic research, the name and related information of the companies that moved may be revealed. Although this information may be open to the public you need to know that this information may be used by people with other ulterior motives. This project will desensitise the company name and information at the stage of chart presentation, such as using A, B, and C to replace them to achieve this purpose.

