# Conclusion

Aiming to make contributions to the research on the dynamic characteristics of tech clusters and industrial concentration, this article not only analyses the distribution of tech clusters in the England area but also conduct regression analysis and spatio-temporal pattern mining. In addition, the relationship between the entry rate of tech companies in England and the different indicators of the clusters (including firms density and the concentration of tech industries) is also quantitatively explained based on the results of the regression model and the spatial autocorrelation test.

In a nutshell, under the current research framework, whether it is the entire area of England or the local tech clusters, the experimental results in the past 20 years (1998-2018) have shown that industrial concentration and company density have a strong relationship with the entry rate of cluster technology companies. For example, the higher the industrial diversity and the greater the density of local technology companies, the higher the entry rate of technology companies in the region. In addition, the visualisation of spatio-temporal patterns also found the shift of cold and hot spots. For instance, compared with England as a whole, the cluster effect of the entry rate in some areas in the north has declined more slowly, while the southwest has changed from a cluster with a high entry rate to a cluster with a low entry rate. These findings can help government planning decision-makers to optimise the investment distribution of science and technology industries in England, thus realising the fair development of resource allocation among the England science and technology industries in the future.

Although the research framework has some limitations, the regression model and spatial autocorrelation analysis methods have good reproducibility in explaining the areas whose administrative divisions are similar to the UK. For the expansion of research directions, this research can refer to Clementi's (2016) analysis framework to investigate the dynamics of a cross-section of enterprises and their implications for aggregate dynamics. In addition, with the development of the technology industry and the trend of globalisation, the government's collection and archiving of more dimensional data of these companies would help to employ quantitative methods to explore the survival mode of tech companies. In addition to a more multi-dimensional quantitative analysis, this research can also focus on studying the impact of corporates' movement in the future, especially the change of the same company address and other corporate indicators such as the size of employees and assets before and after the relocation.

<!-- # Dropped -->

<!-- ## Entry Related Paper -->
<!--  case (Clementi & Palazzo,2016) -->
<!-- This paper provides a framework to study the dynamics of the cross–section of firms and its implications for aggregate dynamics. When calibrated to match a set of moments of the investment process, our model delivers implications for firm dynamics and for the cyclicality of entry and exit that are consistent with the evidence.  -->

<!-- The survival rate increases with size. The growth rate of employment is decreasing with size and age, both unconditionally and conditionally. The size distribution of firms is skewed to the right. When tracking the size distribution over the life a cohort, the skewness declines with age. The entry rate is positively correlated with current and lagged output growth. The exit rate is negatively correlated with output growth and positively associated with future growth.  -->

<!-- Carefully modeling firm–level dynamics turns out to be key. The pro–cyclicality of entry and the positive association between age and firm growth deliver amplification and propagation of aggregate shocks in a plain-vanilla competitive framework. -->

<!-- A positive shock to aggregate productivity leads to an increase in entry. Consistent with the empirical evidence, entrants are smaller than incumbents. The skewness of the distribution of firms over idiosyncratic productivity increases. As the exogenous component of aggregate productivity declines towards its unconditional mean, the new entrants that survive grow in productivity and size. That is, the distribution of idiosyncratic productivity improves. As a result, the response of output is stronger and more persistent than in an environment that abstracts from entry and exit.  -->

<!-- Our numerical experiments reveal that on average, entry and exit account for about one fifth of the above–trend growth experienced by our economy over the 10 years following a 1.5 standard deviation innovation to aggregate productivity. As an alternative metric of the impact of entry and exit on aggregate dynamics, we assessed the effect on persistence. For a version of our model without entry or exit to generate a data–conforming persistence of output, the first–order auto correlation of aggregate productivity shocks must be 0.775. In the benchmark scenario with entry and exit, it needs only be 0.685.  -->

<!-- Last, but not least, we show that according to our model there is a clear causal link between the exceptionally large drop in establishments during the great recession and the painfully low speed of the recovery from it. Whatever its exact nature, the adverse event that initiated the recession had a particularly strong effect on the 2008 and 2009 cohorts, severely reducing the ranks of small but high–conditional–growth plants and thereby suppressing the growth in aggregate labor demand for years to come.  -->

<!-- In spite of the wealth of detail and descriptive realism achieved by the model, our framework could be extended in a variety of dimensions. In particular, we would like to gauge the quantitative effect of our mechanism when imbedded in a genuine general equilibrium framework. Relaxing our assumption that firms of different cohorts share the same technology is also of interest. Assuming, as it appears to be the case in reality, that entrants are more likely to adopt more recent vintages of capital, is likely to further enhance the amplification and propagation mechanism uncovered here.  -->
<!-- end (Clementi & Palazzo,2016) -->


<!-- ## Sample -->

<!-- In order to contribute to the empirical studies that address spatial interaction in terms of long-term migration within the PM-CRs in China, this paper has visualised and simulated the internal migration flows and the potential impacts of inter-city railway planning on those migration flows within the GBA mainly by using the unconstrained gravity models. In addition, the relationships between those migration flows and different indicators, including socio-economic and travel cost factors, have also been quantitatively revealed based on the results of models. -->

<!-- Briefly, the strong connections within the Z-shaped geographic structure including 5 cities are significantly prominent in the current long-term migration pattern for whether the GBA or Gd province, and the migration flows from or to these cities will further increase in the next five years with the implementation of short-term railway planning, especially the flows from or to Dongguan. However, from 2025 to 2035 will witness the closer spatial interaction between the other four cities on the geographical edge of the GBA. These findings can serve the planning decision makers to optimize urban functions and the allocations of public resources to respond to the changes in future migration patterns within the GBA. -->

<!-- Although there are some limitations mentioned in the Chapter 3, the relatively good fitness of the models demonstrates the significant applicability of gravity model in interpreting the spatial interaction between Chinese cities. Furthermore, since there are more and more spatio-temporary movement data provided by mobile-phone network operators or mobile applications that record users’ location changes, the method that using the total daily movement before the Spring Festival can be employed to smaller geographical levels in future studies to overcome the limited availability of long-term migration O-D data. Except for more granular analyses and visualisations, future studies can also be devoted to enriching and optimizing the indicators that introduced into the model employed in this study, especially the indicator of travel cost that might be much complicated in real world. -->
