
```{=latex}
\addcontentsline{toc}{chapter}{Bibliography}
\printbibliography
```
# Appendix A Data Source {-}

```{=latex}
\addtocontents{toc}{\protect\setcounter{tocdepth}{0}}
```

```{r data-source, echo=FALSE, message=FALSE, warning=FALSE}
library(here)
library(tidyverse)
library(knitr)
library(kableExtra)
library(readxl)
library(fs)
options(knitr.kable.NA = '')
read_excel(here("tables", "data_source.xlsx"))%>% 
    knitr::kable(booktabs = TRUE,
                 longtable = TRUE,
                 caption = "Research Data Source and Link")%>%
    kable_styling(position = "center") %>% 
    add_footnote(c("TTWAs means travel to work areas"), notation = "alphabet") %>% 
    row_spec(.,row=0,bold = TRUE) %>% 
    column_spec(1,width = "4.5cm")%>% 
    column_spec(2,width = "8.5cm")
```

`r if (knitr:::is_html_output()) '
# Appendix B Research Log{-}
'`

`r if (knitr:::is_latex_output()) '
# Appendix B Research Log{-}
'`

```{r research-log, echo=FALSE, message=FALSE, warning=FALSE}

options(knitr.kable.NA = '')
read_excel(here("tables", "reproducible_research_log.xlsx"))%>% 
    knitr::kable(booktabs = TRUE,
                 longtable = TRUE,
                 caption = "Research Log and Reproducible Analysis Process")%>%
    kable_styling(position = "center") %>% 
    # add_footnote(c("TTWAs means travel to work areas"), notation = "alphabet") %>% 
    row_spec(.,row=0,bold = TRUE) %>% 
    column_spec(1,width = "4.5cm")%>% 
    column_spec(2,width = "8.5cm")
```

```{=latex}
\addtocontents{toc}{\protect\setcounter{tocdepth}{3}}
\enddocument
```